name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '1.6.8'
      - run: nimble update
      - run: nimble install glfw@#gridmonger 
      - run: nimble -n install nanovg osdialog riff winim https://github.com/johnnovak/koi/
      - run: nim debug
      - run: nim release
